### PR TITLE
universal example

### PR DESCRIPTION
**Pull request by Sinewyk**
follow up to #106 (example isolated and refactored for a flatter tree) and https://github.com/jordangarcia/nuclear-js-react-addons/pull/1 because it was merged and I have a stable commit to base this example on ...

### CODE REVIEW

**Comment by Sinewyk** [comment]
I should probably write some of the components as es6 classes to show that the decorator pattern works and how to use it maybe ?

**Comment by hipertracker** [comment]
Using ES6 classes would be great.

**Comment by Sinewyk** [comment]
ref #24, for everyone to check out working universal example.

**Comment by Sinewyk** [comment]
@hipertracker updated to showcase how to use the addon with es6 for one of the component.

Check the ThreadSection component for full es6 or ThreadListItem component for simply mixin-less but no class.

**Comment by jordangarcia** [comment]
@Sinewyk is this ready to merge?

Example code looks fine to me.

**Comment by Sinewyk** [comment]
Should be good now, just fixed to correct hash for the addons.

**Comment by jordangarcia** [comment]
@Sinewyk awesome, I'm going to go ahead and merge.

I will tag and publish the `nuclear-js-react-addons` as `0.1.0` and we can change the tag here to a semver.

Also I made you a collaborator on that repo so you should be able to manage that stuff w/o me.

**Comment by Sinewyk** [comment]
Yep, saw that, thanks :+1:

**Pull request merged**
