### PR TITLE
Correct getDataBindings getters in README.

### PR DESCRIPTION
**Pull request by HankMcCoy**
I think I got all the bad key paths from issue #31.

### CODE REVIEW

**Comment by HankMcCoy** [comment]
Investigating the broken build. :/

**Comment by HankMcCoy** [comment]
Based on a previous similar commit [having the same problem](https://travis-ci.org/optimizely/nuclear-js/builds/62766756) I'm guessing this is a known build issue you're already working on?

**Comment by bhamodi** [comment]
Hey @HankMcCoy - ya don't worry about the build failure. It has nothing to do with your README update. :)

**Comment by bhamodi** [comment]
LGTM. Thanks @HankMcCoy.

**Pull request merged**
